language: python

matrix:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true
  - python: "nightly"
    dist: xenial
    sudo: true
  - os: osx
    language: sh
    python: "3.7"
    before_install:
        #- brew update
        - brew upgrade python3
        - python3 -m venv venv
        - source venv/bin/activate
  - os: windows
    language: sh
    python: "3.7"
    before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m venv venv
        - venv/Scripts/activate.bat
        - python -m pip install --upgrade pip wheel
install:
    - "pip install -r requirements-test.txt"
    - "flit install"
script:
    pytest -vv --cov aiorun tests/
after_success:
    coveralls
